### ISSUE TITLE
Prisma error

### ISSUE THREAD

**Issue by rossman22590** [techulus/manage-prompt#107]
Error [PrismaClientValidationError]: Invalid client engine type, please use `library` or `binary`
    at <unknown> (webpack-internal:///(rsc)/./node_modules/@prisma/client/runtime/edge.js:29)
    at ss (webpack-internal:///(rsc)/./node_modules/@prisma/client/runtime/edge.js:12:65)
    at new t (webpack-internal:///(rsc)/./node_modules/@prisma/client/runtime/edge.js:29:3661)
    at eval (webpack-internal:///(rsc)/./lib/utils/db.ts:10:48)
    at (rsc)/./lib/utils/db.ts (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\app\api\v1\token\route.js:93:1)
    at __webpack_require__ (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\edge-runtime-webpack.js:293:21)
    at eval (webpack-internal:///(rsc)/./app/api/v1/token/route.ts:18:71)
    at (rsc)/./app/api/v1/token/route.ts (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\app\api\v1\token\route.js:60:1)
    at __webpack_require__ (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\edge-runtime-webpack.js:293:21)

**Comment by arjunkomath** [comment]
Should be fixed with the latest changed

**Comment by rossman22590** [comment]
still happening

**Comment by arjunkomath** [comment]
> still happening

Are you using Prisma accelerate?

**Comment by rossman22590** [comment]
yes in the code it uses this , i use db from neon what do you use?

**Comment by rossman22590** [comment]
everything is filled in properly  - i connect db and npx push npx migrate all that and it runs but once it starts prisma error DB is populated with tables in NEON

**Comment by rossman22590** [comment]
same issue on dev and main ✓ Compiled /middleware in 1802ms (475 modules)
 ⨯ Error [PrismaClientValidationError]: Invalid client engine type, please use `library` or `binary`
    at <unknown> (webpack-internal:///(middleware)/./node_modules/@prisma/client/runtime/edge.js:29)
    at ss (webpack-internal:///(middleware)/./node_modules/@prisma/client/runtime/edge.js:12:65)
    at new t (webpack-internal:///(middleware)/./node_modules/@prisma/client/runtime/edge.js:29:3661)
    at eval (webpack-internal:///(middleware)/./lib/utils/db.ts:10:16)
    at (middleware)/./lib/utils/db.ts (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\middleware.js:73:1)
    at __webpack_require__ (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\edge-runtime-webpack.js:285:21)
    at eval (webpack-internal:///(middleware)/./auth.ts:11:71)
    at (middleware)/./auth.ts (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\middleware.js:62:1)
    at __webpack_require__ (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\edge-runtime-webpack.js:37:33)
    at fn (file://C:\Users\Ross\Desktop\manage-prompt-main\.next\server\edge-runtime-webpack.js:285:21)

**Comment by arjunkomath** [comment]
You can use any Postgres DB, but it has to connect via Prisma accelerate.

**Comment by rossman22590** [comment]
which to u use?

**Comment by arjunkomath** [comment]
I use Fly Postgres.

**Comment by rossman22590** [comment]
will supabase work, since neon does not

**Comment by rossman22590** [comment]
used fly it worked

**Comment by rossman22590** [comment]
Hey so I tried on your platform to , I opened a ticket wanna try your
platform but when I do my AI just keeps saying the same thing over and over
any guidance on the variable part and how to sent input data to model?

**Comment by arjunkomath** [comment]
Sorry, unfortunately I don’t have the bandwidth to support self hosted solutions.

**Comment by rossman22590** [comment]
I'm using your hosted platform actually now and having the issue.

**Comment by rossman22590** [comment]
I'm logged into your system to us that instead .
